version: '3.8'
services:
  db:
    container_name: bp-db
    build: ./database
    environment:
      MYSQL_ROOT_PASSWORD: desaas
      MYSQL_DATABASE: budget_planning
      MYSQL_USER: tyuser
      MYSQL_PASSWORD: de1234
      MYSQL_TCP_PORT: 3307
      LANG: C.UTF_8
    ports:
      - "3307:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_turkish_ci']
    networks:
      - my-network

  app:
    image: budget-planning
    container_name: budget-planning-app
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://bp-db:3307/budget_planning?verifyServerCertificate=false&useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&autoReconnect=true
    ports:
      - "8088:8088"
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network:
    driver: bridge
